#include <gl/gl.h>

#include "util.h"
#include "glext.h"
#include "wglext.h"
 
#define LOAD_GLFUNCTION(func_name,token_name) func_name = (PFN##token_name##PROC) LoadGLFunction (#func_name);
#define DECLARE_GLFUNCTION_IMPL(func_name,token_name) PFN##token_name##PROC func_name;
/* DECLARE_GLFUNCTION_IMPL (wglCreateContextAttribsARB, WGLCREATECONTEXTATTRIBSARB) */
/* DECLARE_GLFUNCTION_IMPL (wglChoosePixelFormatARB, WGLCHOOSEPIXELFORMATARB) */
DECLARE_GLFUNCTION_IMPL (glUseProgram, GLUSEPROGRAM)
DECLARE_GLFUNCTION_IMPL (glCreateProgram, GLCREATEPROGRAM)
DECLARE_GLFUNCTION_IMPL (glDeleteShader, GLDELETESHADER)
DECLARE_GLFUNCTION_IMPL (glLinkProgram, GLLINKPROGRAM)
DECLARE_GLFUNCTION_IMPL (glShaderSource, GLSHADERSOURCE)
DECLARE_GLFUNCTION_IMPL (glAttachShader, GLATTACHSHADER)
DECLARE_GLFUNCTION_IMPL (glGenBuffers, GLGENBUFFERS)
DECLARE_GLFUNCTION_IMPL (glBindBuffer, GLBINDBUFFER)
DECLARE_GLFUNCTION_IMPL (glBufferData, GLBUFFERDATA)
DECLARE_GLFUNCTION_IMPL (glCreateShader, GLCREATESHADER)
DECLARE_GLFUNCTION_IMPL (glCompileShader, GLCOMPILESHADER)
DECLARE_GLFUNCTION_IMPL (glVertexAttribPointer, GLVERTEXATTRIBPOINTER)
DECLARE_GLFUNCTION_IMPL (glEnableVertexAttribArray, GLENABLEVERTEXATTRIBARRAY)
DECLARE_GLFUNCTION_IMPL (glGenVertexArrays, GLGENVERTEXARRAYS)
DECLARE_GLFUNCTION_IMPL (glBindVertexArray, GLBINDVERTEXARRAY)
DECLARE_GLFUNCTION_IMPL (glGetShaderiv, GLGETSHADERIV)
DECLARE_GLFUNCTION_IMPL (glGetShaderInfoLog, GLGETSHADERINFOLOG)
DECLARE_GLFUNCTION_IMPL (glGetUniformLocation, GLGETUNIFORMLOCATION) 
DECLARE_GLFUNCTION_IMPL (glUniform4f, GLUNIFORM4F)
DECLARE_GLFUNCTION_IMPL (glGenerateMipmap, GLGENERATEMIPMAP)
DECLARE_GLFUNCTION_IMPL (glActiveTexture, GLACTIVETEXTURE)
DECLARE_GLFUNCTION_IMPL (glUniform1i, GLUNIFORM1I)

void 
LoadGLFunctionPointers (void)
{
    LOAD_GLFUNCTION (glUseProgram, GLUSEPROGRAM)
    LOAD_GLFUNCTION (glCreateProgram, GLCREATEPROGRAM)
    LOAD_GLFUNCTION (glDeleteShader, GLDELETESHADER)
    LOAD_GLFUNCTION (glLinkProgram, GLLINKPROGRAM)
    LOAD_GLFUNCTION (glShaderSource, GLSHADERSOURCE)
    LOAD_GLFUNCTION (glAttachShader, GLATTACHSHADER)
    LOAD_GLFUNCTION (glGenBuffers, GLGENBUFFERS)
    LOAD_GLFUNCTION (glBindBuffer, GLBINDBUFFER)
    LOAD_GLFUNCTION (glBufferData, GLBUFFERDATA)
    LOAD_GLFUNCTION (glCreateShader, GLCREATESHADER)
    LOAD_GLFUNCTION (glCompileShader, GLCOMPILESHADER)
    LOAD_GLFUNCTION (glVertexAttribPointer, GLVERTEXATTRIBPOINTER)
    LOAD_GLFUNCTION (glEnableVertexAttribArray, GLENABLEVERTEXATTRIBARRAY)
    LOAD_GLFUNCTION (glGenVertexArrays, GLGENVERTEXARRAYS)
    LOAD_GLFUNCTION (glBindVertexArray, GLBINDVERTEXARRAY)
    LOAD_GLFUNCTION (glGetShaderiv, GLGETSHADERIV)
    LOAD_GLFUNCTION (glGetShaderInfoLog, GLGETSHADERINFOLOG)
    LOAD_GLFUNCTION (glGetUniformLocation, GLGETUNIFORMLOCATION) 
    LOAD_GLFUNCTION (glUniform4f, GLUNIFORM4F)
    LOAD_GLFUNCTION (glGenerateMipmap, GLGENERATEMIPMAP)
    LOAD_GLFUNCTION (glActiveTexture, GLACTIVETEXTURE)
    LOAD_GLFUNCTION (glUniform1i, GLUNIFORM1I)
    /* LOAD_GLFUNCTION (wglCreateContextAttribsARB, WGLCREATECONTEXTATTRIBSARB) */
    /* LOAD_GLFUNCTION (wglChoosePixelFormatARB, WGLCHOOSEPIXELFORMATARB) */
}
